# Generated by Django 4.2.16 on 2026-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=200)),
                ('section_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('punishment', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
