# Generated by Django 4.2.16 on 2026-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('extracted_text', models.TextField()),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
